version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=exchange_matching
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    expose:
      - "5432"

  server:
    build: .
    command: bash -c "./run.sh db 4 5"
    volumes:
      - .:/servercode
    ports:
      - "12345:12345"
    depends_on:
      - db
